# speech-recognition-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: speech-recognition-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speech-recognition
  template:
    metadata:
      labels:
        app: speech-recognition
    spec:
      containers:
      - name: speech-recognition
        image: your-docker-repo/speech-recognition:latest
        ports:
        - containerPort: 8002
---
apiVersion: v1
kind: Service
metadata:
  name: speech-recognition-service
spec:
  type: NodePort
  selector:
    app: speech-recognition
  ports:
    - port: 8002
      targetPort: 8002
      nodePort: 30003
